site_name: PyMdown Mahjong
site_description: Python Markdown extension to render Mahjong tiles and hands.
site_url: https://pymdownx-mahjong.tylernguyen.codes/

repo_name: tylernguyen/pymdownx-mahjong
repo_url: https://github.com/tylernguyen/pymdownx-mahjong

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Automatic Mode Enabled. Click to Toggle Dark Mode."
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-night-outline
        name: "Dark Mode Enabled. Click to Toggle Light Mode."
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: "Light Mode Enabled. Click to Toggle Automatic Mode."
  icon:
    logo: lucide/book
    repo: simple/refinedgithub
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.follow


markdown_extensions:
  - pymdownx_mahjong:
      theme: auto
      closed_kan_style: outer
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mahjong
          class: mahjong
          validator: !!python/name:pymdownx_mahjong.superfences_validator
          format: !!python/name:pymdownx_mahjong.superfences_formatter
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/mahjong.css

nav:
  - README: "index.md"
  - examples.md
  - license.md

plugins:
  - search
