name: Upload CSS to Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-css:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Upload `mahjong.css`
        uses: softprops/action-gh-release@v2
        with:
          files: pymdownx_mahjong/css/mahjong.css
